---
title: '2.3.1 Basic Commands'
author: "Juan Cabrera"
date: "8/13/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## In this lab, we will review simple R commands. 

```{r}
# Creates a vector named x
x <- c(1,3,2,5)
x
```
```{r}
# Creates two vectors named x and y
x = c(1,6,2)
x
y = c(1,4,3)
```


```{r}
# Length of vectors x and y
length(x)
length(y)
# Sum of entries in x and y
x+y 
```
```{r}
# ls function list all the objects such as data and functions
ls()
# rm function deletes any objects we don't want
rm(x,y)
# To remove all at once 
rm(list=ls())
```

```{r}
# matrix() is a function to create a matrix
?matrix
# A simple square matrix with 2 rows and 2 columns.
x=matrix(data=c(1,2,3,4),nrow=2,ncol=2)
x
# Alternative way of writing the matrix
x=matrix(c(1,2,3,4),2,2)
x
# By default, R creates matrices by successively filling in columns
# Alternative, byrow=TRUE option can be used to populate the rows
matrix(c(1,2,3,4),2,2,byrow=TRUE)
```
```{r}
# sqrt() is the square root function - will take the sqr of each element
sqrt(x)

# x^2 is the power 2 function which raises each element of x
x^2
```
```{r}
# rnorm() is the function that generates a vector of random normal variables
# with first argument n the sample size with mean of 0 and 
# standard deviation of 1; mean and sd can be changed by using mean and sd
x=rnorm(50)
x
y = x+rnorm(50, mean=50, sd=1)
cor(x,y)

# set.seed() keeps the exact same set of random numbers; the argument is 
# arbitrary; this function is useful to reproduce results
set.seed(1303)
rnorm(50)

set.seed(3)
y=rnorm(100)
y
# Mean of each element
mean(y)
# Standard deviation of the vector of numbers not of each element
var(y)
# Sqrt of each element
sqrt(y)
# Sqrt of the variance above, not of each element
sqrt(var(y))
# Standard deviation of the vector of numbers not of each each element
sd(y)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
